# Generated by Django 3.1.1 on 2020-09-08 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=60, null=True, verbose_name='your task')),
                ('priority', models.CharField(choices=[('0', '!'), ('1', '!!'), ('2', '!!!')], default=0, help_text='Set priority of this task', max_length=3, null=True, verbose_name='priority')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='enter description')),
                ('status', models.CharField(choices=[('0', 'In progress'), ('1', 'Completed')], default=0, help_text='Set status of this task', max_length=15, null=True, verbose_name='status')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-date_added'],
            },
        ),
    ]
