# Generated by Django 3.1.1 on 2020-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0002_auto_20200903_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=60, null=True, verbose_name='the user task')),
                ('priority', models.CharField(choices=[('0', ''), ('1', '!'), ('2', '!!'), ('3', '!!!')], default=0, help_text='Set priority of task', max_length=3, null=True)),
                ('description', models.CharField(max_length=150, null=True, verbose_name='enter description for task')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ManyToManyField(to='todo.Category', verbose_name='list of categories')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-date_added'],
            },
        ),
    ]
