# Generated by Django 3.1.1 on 2020-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_category_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(to='todo.Category', verbose_name='what category?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='enter description of this task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('0', ''), ('1', '!'), ('2', '!!'), ('3', '!!!')], default=0, help_text='Set priority of this task', max_length=3, null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(help_text='name of your task', max_length=60, null=True, verbose_name='your task'),
        ),
    ]
