# Generated by Django 3.1.1 on 2020-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20200910_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default=0, max_length=12, null=True),
        ),
    ]
