# Generated by Django 3.1.1 on 2020-09-07 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyBudget', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('date_purchased', models.DateTimeField()),
                ('userProfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expenseprofile')),
            ],
            options={
                'verbose_name_plural': 'ExpenseItems',
                'ordering': ['date_purchased'],
            },
        ),
    ]
