# Generated by Django 3.1.1 on 2020-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='date_purchased',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='monthlyBudget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
